const FOOD_LIST_REQUEST = "FOOD_LIST_REQUEST";
const FOOD_LIST_SUCCESS = "FOOD_LIST_SUCCESS";
const FOOD_LIST_FAILURE = "FOOD_LIST_FAILURE";

const SEARCH_FOOD_LIST_REQUEST = "SEARCH_FOOD_LIST_REQUEST";
const SEARCH_FOOD_LIST_SUCCESS = "SEARCH_FOOD_LIST_SUCCESS";
const SEARCH_FOOD_LIST_FAILURE = "SEARCH_FOOD_LIST_FAILURE";

const FILTER_FOOD_LIST_REQUEST = "FILTER_FOOD_LIST_REQUEST";
const FILTER_FOOD_LIST_SUCCESS = "FILTER_FOOD_LIST_SUCCESS";
const FILTER_FOOD_LIST_FAILURE = "FILTER_FOOD_LIST_FAILURE";

const SEARCH_FUNCTION = "SEARCH_FUNCTION"
const TOGGLE_FILTER = "TOGGLE_FILTER "
export default {
    FOOD_LIST_REQUEST,
    FOOD_LIST_SUCCESS,
    FOOD_LIST_FAILURE,
    SEARCH_FOOD_LIST_REQUEST,
    SEARCH_FOOD_LIST_SUCCESS,
    SEARCH_FOOD_LIST_FAILURE,
    SEARCH_FUNCTION,
    FILTER_FOOD_LIST_REQUEST,
    FILTER_FOOD_LIST_SUCCESS,
    FILTER_FOOD_LIST_FAILURE,
    TOGGLE_FILTER 

}