const FOOD_LIST_REQUEST = "FOOD_LIST_REQUEST";
const FOOD_LIST_SUCCESS = "FOOD_LIST_SUCCESS";
const FOOD_LIST_FAILURE = "FOOD_LIST_FAILURE";


export default {
    FOOD_LIST_REQUEST,
    FOOD_LIST_SUCCESS,
    FOOD_LIST_FAILURE
}