const SINGLE_FOOD_LIST_REQUEST = "SINGLE_FOOD_LIST_REQUEST";
const SINGLE_FOOD_LIST_SUCCESS = "SINGLE_FOOD_LIST_SUCCESS";
const SINGLE_FOOD_LIST_FAILURE = "SINGLE_FOOD_LIST_FAILURE";


export default {
    SINGLE_FOOD_LIST_REQUEST,
    SINGLE_FOOD_LIST_SUCCESS,
    SINGLE_FOOD_LIST_FAILURE
}